spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/istp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  date:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
