spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/istp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true